/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SprintCandidateDetailsDto } from '../../models/sprint-candidate-details-dto';

export interface ApiSprintCandidatesDetailsIdGet$Plain$Params {
  id: string;
}

export function apiSprintCandidatesDetailsIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiSprintCandidatesDetailsIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SprintCandidateDetailsDto>> {
  const rb = new RequestBuilder(rootUrl, apiSprintCandidatesDetailsIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SprintCandidateDetailsDto>;
    })
  );
}

apiSprintCandidatesDetailsIdGet$Plain.PATH = '/api/SprintCandidates/details/{id}';
