/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SprintCandidates } from '../../models/sprint-candidates';

export interface ApiSprintCandidatesPost$Json$Params {
      body?: SprintCandidates
}

export function apiSprintCandidatesPost$Json(http: HttpClient, rootUrl: string, params?: ApiSprintCandidatesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SprintCandidates>> {
  const rb = new RequestBuilder(rootUrl, apiSprintCandidatesPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SprintCandidates>;
    })
  );
}

apiSprintCandidatesPost$Json.PATH = '/api/SprintCandidates';
