/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SprintCandidateSummaryDto } from '../../models/sprint-candidate-summary-dto';

export interface ApiSprintCandidatesSummaryGet$Json$Params {
}

export function apiSprintCandidatesSummaryGet$Json(http: HttpClient, rootUrl: string, params?: ApiSprintCandidatesSummaryGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SprintCandidateSummaryDto>>> {
  const rb = new RequestBuilder(rootUrl, apiSprintCandidatesSummaryGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SprintCandidateSummaryDto>>;
    })
  );
}

apiSprintCandidatesSummaryGet$Json.PATH = '/api/SprintCandidates/summary';
