/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SprintCandidates } from '../../models/sprint-candidates';

export interface ApiSprintCandidatesSearchGet$Json$Params {
  query?: string;
}

export function apiSprintCandidatesSearchGet$Json(http: HttpClient, rootUrl: string, params?: ApiSprintCandidatesSearchGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SprintCandidates>>> {
  const rb = new RequestBuilder(rootUrl, apiSprintCandidatesSearchGet$Json.PATH, 'get');
  if (params) {
    rb.query('query', params.query, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SprintCandidates>>;
    })
  );
}

apiSprintCandidatesSearchGet$Json.PATH = '/api/SprintCandidates/search';
