/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SprintCandidates {
  acceptanceCriteria?: string | null;
  aiInsights?: Array<string> | null;
  description?: string | null;
  id?: string | null;
  lastUpdated?: string;
  linkedDocs?: Array<string> | null;
  parentItemId?: string | null;
  priority?: string | null;
  status?: string | null;
  tags?: Array<string> | null;
  title?: string | null;
  type?: string | null;
}
