/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SprintCandidateSummaryDto {
  aiInsights?: Array<string> | null;
  id?: string | null;
  lastUpdated?: string;
  priority?: string | null;
  status?: string | null;
  tags?: Array<string> | null;
  title?: string | null;
}
