/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SprintCandidateDetailsDto {
  acceptanceCriteria?: string | null;
  description?: string | null;
  id?: string | null;
  linkedDocs?: Array<string> | null;
  title?: string | null;
}
